[package]
name = "candb"
version = "1.0.0"
description = "Certified assets on Internet Computer"
repository = "https://github.com/fermartz/motoko-certified-assets"

[dependencies]
base = "0.9.3"
ic-certification = "0.1.1"
sha2 = "0.0.2"
stableheapbtreemap = "1.3.0"
map = "8.1.0"